name: Evaluate Latest SCT DeepSeg Runtime

# Only run this when explicitly requested, as it can be quite slow
on: [workflow_dispatch]

env:
    # Force APT to run non-interactively (prevent occasional hangs)
    DEBIAN_FRONTEND: 'noninteractive'
    # Turns on color output for pytest
    PY_COLORS: "1"
    # Disable progress bars for less verbose output
    PIP_PROGRESS_BAR: "off"
    SCT_PROGRESS_BAR: "off"
    # Convenience variables
    SCT_BIN_PATH: "./spinalcordtoolbox/bin"
    RESULT_PATH: "./ci_results"
    # The DeepSeg task we want to test
    DEEPSEG_TASK: "spinalcord"

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Clone SCT master branch
      uses: GuillaumeFalourd/clone-github-repo-action@v2.1
      with:
        depth: 1
        owner: 'spinalcordtoolbox'
        repository: 'spinalcordtoolbox'
    - name: Install SCT
      run: |
        cd spinalcordtoolbox
        ./install_sct -y
        cd ..
    - name: Check dependencies
      run: |
        # We don't add the bin to the Path to ensure its acting like a "remote" install.
        # This it to keep parity with how the script would be run locally or on SLURM-based systems.
        ./spinalcordtoolbox/bin/sct_check_dependencies
    - name: Prepare Images
      run: python setup.py -s $SCT_BIN_PATH
    - name: Run the Timings
      run: python run.py -s $SCT_BIN_PATH -t $DEEPSEG_TASK -r $RESULT_PATH
    - name: Make Results Available
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu_results
        path: ${{ env.RESULT_PATH }}

  macos:
    runs-on: macos-13
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Clone SCT master branch
        uses: GuillaumeFalourd/clone-github-repo-action@v2.1
        with:
          depth: 1
          owner: 'spinalcordtoolbox'
          repository: 'spinalcordtoolbox'
      - name: Install SCT
        run: |
          cd spinalcordtoolbox
          ./install_sct -y
          cd ..
      - name: Check dependencies
        run: |
          # We don't add the bin to the Path to ensure its acting like a "remote" install.
          # This it to keep parity with how the script would be run locally or on SLURM-based systems.
          ./spinalcordtoolbox/bin/sct_check_dependencies
      - name: Prepare Images
        run: python setup.py -s $SCT_BIN_PATH
      - name: Run the Timings
        run: python run.py -s $SCT_BIN_PATH -t $DEEPSEG_TASK -r $RESULT_PATH
      - name: Make Results Available
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_results
          path: ${{ env.RESULT_PATH }}

  windows:
    runs-on: windows-2022
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Clone SCT master branch
        uses: GuillaumeFalourd/clone-github-repo-action@v2.1
        with:
          depth: 1
          owner: 'spinalcordtoolbox'
          repository: 'spinalcordtoolbox'
      - name: Install SCT
        shell: cmd
        run: |
          cd spinalcordtoolbox
          install_sct.bat
          cd ..
      - name: Check dependencies
        run: |
          ./spinalcordtoolbox/bin/sct_check_dependencies
      - name: Prepare Images
        # Holy hell I hate Windows
        shell: cmd
        run: python setup.py -s ${{ env.SCT_BIN_PATH }}
      - name: Run the Timings
        shell: cmd
        run: python run.py -s ${{ env.SCT_BIN_PATH }} -t ${{ env.DEEPSEG_TASK }} -r ${{ env.RESULT_PATH }}
      - name: Make Results Available
        uses: actions/upload-artifact@v4
        with:
          name: windows_results
          path: ${{ env.RESULT_PATH }}