name: Evaluate Latest SCT DeepSeg Runtime

# Only run this when explicitly requested, as it can be quite slow
on: [workflow_dispatch]

env:
    # Force APT to run non-interactively (prevent occasional hangs)
    DEBIAN_FRONTEND: 'noninteractive'
    # Turns on color output for pytest
    PY_COLORS: "1"
    # Disable progress bars for less verbose output
    PIP_PROGRESS_BAR: "off"
    SCT_PROGRESS_BAR: "off"

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Clone SCT master branch
      uses: GuillaumeFalourd/clone-github-repo-action@v2.1
      with:
        depth: 1
        branch: 'master'
        owner: 'spinalcordtoolbox'
        repository: 'spinalcordtoolbox'
    - name: Install SCT
      run: |
        cd spinalcordtoolbox
        ./install_sct -y
        cd ..
    - name: Check dependencies
      run: |
        # We don't add the bin to the Path to ensure its acting like a "remote" install.
        # This it to keep parity with how the script would be run locally or on SLURM-based systems.
        ./spinalcordtoolbox/bin/sct_check_dependencies
    - name: Prepare Images
      run: |
        # Replace the "demo" config with one we have set-up for this CI
        rm config.json
        cp ./.github/ci_resources/config.json .
        
        # Run the setup
        python setup.py
        
        # TMP: List the current directory
        ls *
